### ISSUE TITLE
Adding axios to React component

### ISSUE THREAD

**Issue by hengel2810** [pastahito/electron-react-webpack#1]
Hello,

I want to use axios to load some server-data to one of my components. I use the following line of code at the top of the component to import the package: `import axios from 'axios';`

This gives me the following error in terminal:

`ERROR in ./app/src/components/APIController.js
Module not found: Error: Can't resolve 'axios' in ......`

Hope somebody can help how to import the npm loaded package.

**Comment by pastahito** [comment]
Hello @hengel2810, I cloned the repo and tried `npm install --save axios` then I went to app/src/App.jsx and add 
```javascript
import axios from 'axios';

axios.get('https://jsonplaceholder.typicode.com/posts/1')
  .then(function (response) {
    console.log(response);
  })
  .catch(function (error) {
    console.log(error);
  });
```
just to test it, and it worked. This might be not helpful, but I'm not able to reproduce your error.

**Comment by hengel2810** [comment]
Found the problem. I've cloned your repo and added my components from my react web application but I forgot to add axios to the dependencies in package.json. Thanks for your fast answer. Silly mistake.  Issue can be closed.

**Comment by pastahito** [comment]
Glad you fixed it.
