### ISSUE TITLE
electron-renderer

### ISSUE THREAD

**Issue by holtwick** [pastahito/electron-react-webpack#10]
I think this should be `electron-renderer`?

https://github.com/pastahito/electron-react-webpack/blob/0ca6107cb2443417c5ad9c681efa34b17b08ec82/webpack.config.js#L7

**Comment by renato-rg** [comment]
@holtwick I'm not sure

**Comment by holtwick** [comment]
`electron-main` is node.js and `electron-renderer` the Chrome JS engine. Since the code goes into the window it is Chrome-land and therefore I would vote for the later :)

**Comment by holtwick** [comment]
Also see for comparison https://github.com/chentsulin/electron-react-boilerplate/blob/master/webpack.config.renderer.dev.js

And https://webpack.js.org/concepts/targets/

Anyway, shouldn't make a big difference.
