### ISSUE TITLE
Include on README how to build the project

### ISSUE THREAD

**Issue by ichbinedgar** [pastahito/electron-react-webpack#7]
Hi,
It seems that this boilerplate is missing the information about how to package the project , so it can be distributed.

**Comment by TheAifam5** [comment]
As I see, the packaging process does not exists.
You can also use the electron-packager in your project which isn't hard to integrate.

**Comment by ichbinedgar** [comment]
I see,  sorry. I'm new on electron. Most of the boilerplates for react contain the "build" script so I thought this react electron version was missing that.

**Comment by victorgianvechio** [comment]
the error still even after updating package.json... Any solution?

**Comment by ichbinedgar** [comment]
> the error still even after updating package.json... Any solution?

I'm not sure what do you mean, but this is related to add documentation about how to build the project

**Comment by victorgianvechio** [comment]
@ichbinedgar sorry, wrong issue
